config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'List was successfully deleted.' }
      format.json { head :no_content }
  end
end

private
  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, except: [:create]

def create
  @task = @list.tasks.create(task_params)
  redirect_to @list
end

def destroy
  if @task.destroy
    flash[:success] = "Task was successfully deleted."
  else
    flash[:error] = "Task could not be deleted."
  end
  redirect_to @list
end

def complete
  @task.update_attribute(:completed_at, Time.now)
  redirect_to @list, notice: "Task completed"
end

private
def set_list
  @list = List.find(params[:list_id])
end

def set_task
  @task = @list.tasks.find(params[:id])
end

def task_params
  params[:task].permit(:content)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
  </head>
  <body>
    <header>
  <div class="title">
    <%= link_to "SIMPLE TODO LISTS", lists_path %>
  </div>
  <div class="sub_title">
    <h2>By Aleksandr Vorobei</h2>
    </div>
</header>
    <div class = "container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1 class = "list_title">Editing List</h1>

<div class = "forms">
  <%= render 'form', list: @list %>
</div>

<div class = "links">
  <%= link_to 'Cancel', lists_path %>
</div>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
<div class="index_row clearfix">
  <h2 class="list_title"><%= link_to list.title, list %></h2>
  <p class="list_sub_title"><%= list.description %></p>
</div>
<% end %>

<div class="links">
  <%= link_to "New List", new_list_path %>
</div>

app/views/lists/new.html.erb
<h1 class = "list_title">New List</h1>

<div class = "forms">
  <%= render 'form', list: @list %>
</div>

<div class = "links">
  <%= link_to 'Back', lists_path %>
</div>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class = "list_title"><%= @list.title %></h2>
<p class = "list_sub_title"><%= @list.description %></p>

<div id= "tasks_wrapper">
  <%= render @list.tasks %>
  <div id= "form">
    <%= render "tasks/form" %>
  </div>
</div>

<div class = "links">
  <%= link_to 'Edit', edit_list_path(@list) %> |
  <%= link_to 'Delete', list_path(@list), method: :delete, data: {confirm: "Are you sure?"} %> |
  <%= link_to 'Back', lists_path %>
</div>

app/views/tasks/_form.html.erb
<%= form_for([@list, @list.tasks.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New task" %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<div class = "row clearfix">
  <% if task.completed? %>
    <div class = "complete">
      <%= link_to complete_list_task_path(@list, task.id), method: :patch do %>
        <i style = "opacity: 0.4;" class = "fa fa-check"></i>
      <% end %>
    </div>
    <div class = "task">
      <p style = "opacity: 0.4;"><strike><%= task.content %></strike></p>
    </div>
    <div class = "trash">
      <%= link_to list_task_path(@list, task.id), method: :delete, data: {confirm: "Are you sure?"} do %>
        <i class = "fa fa-trash"></i>
      <% end %>
    </div>
    <% else %>
    <div class = "complete">
      <%= link_to complete_list_task_path(@list, task.id), method: :patch do %>
        <i class = "fa fa-check"></i>
      <% end %>
    </div>
    <div class = "task">
      <p><%= task.content %></p>
    </div>
    <div class = "trash">
      <%= link_to list_task_path(@list, task.id), method: :delete, data: {confirm: "Are you sure?"} do %>
        <i class = "fa fa-trash"></i>
      <% end %>
    </div>
    <% end %>
</div>